title: "Swiftbits"
description: "Swift snippets, tips, resources, and links."
tagline: "Short doses of Swift"
latestSwift: 3.0

keywords:
 - swift
 - swift-lang
 - ios
 - osx
 - mac
 - swiftbits
 - snippets
 - resources
 - tips
 - links
author:
  name: "Reda Lemeden"

baseurl: ""
feed: http://feedpress.me/swiftbits
future: false
limit_posts: 0
paginate: 5
paginate_path: "/page-:num"
show_drafts: false
source: source
twitter: https://twitter.com/swiftbitsies
url: https://swiftbits.redalemeden.com

gems: [jekyll-sitemap, jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:title/
exclude: [
  "node_modules",
  "gulp.js",
  "gulpfile.coffee",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

keep_files: [
  "css",
  "scripts"
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
