title: "Swiftbits"
description: "Swift snippets, tips, resources, and links."
tagline: "Short doses of Swift"
latestSwift: 2.0ß6
keywords:
 - swift
 - swift-lang
 - ios
 - osx
 - mac
 - swiftbits
 - snippets
 - resources
 - tips
 - links
author:
  name: "Reda Lemeden"

baseurl: ""
url: http://swiftbits.redalemeden.com
future: false
show_drafts: false
paginate: 10
paginate_path: "/page-:num"
limit_posts: 0
gems:
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:title/
exclude: [
  "bower.json",
  "node_modules",
  "gulp.js",
  "gulpfile.coffee",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
